---

name: actionlint
description: ":octocat: Static checker for GitHub Actions workflow files"

#branding: # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
#  icon: _
#  color: _

runs:
  using: composite
  steps:
    - name: "Download Action Lint"
      shell: bash
      run: ${{ github.action_path }}/scripts/download-actionlint.bash latest ${{ runner.temp }}

    - name: "Run Action Lint"
      shell: bash
      run: ${{ runner.temp }}/actionlint -color
