name: Download script
on:
  push:
    paths:
      - scripts/download-actionlint.bash
      - scripts/test-download-actionlint.bash
  pull_request:
    paths:
      - scripts/download-actionlint.bash
      - scripts/test-download-actionlint.bash
  workflow_dispatch:

jobs:
  download:
    name: Test download script
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/test-download-actionlint.bash
        shell: bash
